apiVersion: v2
name: nginx    
description: Nginx Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: nginx
    repository: https://charts.helm.sh/stable 
    tags:
      - bitnami-common
    version: 1.13.1
