apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-appsets
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: my-apps
  source:
    repoURL: https://github.com/nasirudheen/argo-nginx.git
    targetRevision: main 
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
