apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-tenants
spec:
  generators:
    - gi
        repoURL: https://github.com/nasirudheen/argo-nginx.git
        revision: main
        files:
          - path: "argocd/tenants-discovery/**/config.json"
  template:
    metadata:
      name: cluster2-temp1
    spec:
      project: my-apps
      source:
        repoURL: https://github.com/nasirudheen/argo-nginx.git 
        targetRevision: main
        path: 'tenants/{{tenant.id}}/nginx'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{k8s_cluster.address}}'
        namespace: '{{k8s_cluster.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

